import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css?v.1";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { SessionProvider } from "./context/SessionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, minHeight: '100vh', display: 'flex', flexDirection: 'column' }}
      >
        <SessionProvider>
          <Header />
          <div className="main-content">{children}</div>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
